- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no
  vars:
    requests_cpu: "{{ requests_cpu | default('1') }}"
    limits_cpu: "{{ limits_cpu if limits_cpu is defined else '2' }}"
    requests_memory: "{{ requests_memory if requests_memory is defined else '2Gi' }}"
    limits_memory: "{{ limits_memory if limits_memory is defined else '5Gi' }}"

  tasks:
  
    # Ensure we have the basic details 
    - fail: msg="Cancelling Job, Namespace not correctly specified"
      when: namespace is undefined and namespace != ""

    # - fail: msg="Cancelling Job, Namespace does not exist on cluster"
    #   when: namespace is undefined

    # Override EDA Vars if Playbook has been initiated via EDA 
    - name: Include EDA Vars when defined
      ansible.builtin.include_tasks: 'var_list.yaml'
      when: ansible_eda is defined

    # Do the work...
    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ namespace }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
