- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no
  vars:
    namespace: 'testing'
    requests_cpu: '1'
    limits_cpu: '2'
    requests_memory: '2Gi'
    limits_memory: '5Gi'

  tasks:
  
    - fail: msg="Cancelling Job, Namespace not correctly specified"
      when: namespace is undefined and namespace != ""

    # - fail: msg="Cancelling Job, Namespace does not exist on cluster"
    #   when: namespace is undefined

    - name: Include EDA Vars when defined
      ansible.builtin.include_tasks: 'var_list.yaml'
      when: ansible_eda is defined

    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ namespace }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
