- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Setting default values 
      ansible.builtin.set_fact:
        namespace: " {{ namespace | default('testing') }} "
        requests_cpu: "{{ requests_cpu | default('1') }}"
        limits_cpu: "{{ limits_cpu | default('2') }}"
        requests_memory: "{{ requests_memory | default('2Gi') }}"
        limits_memory: "{{ limits_memory | default('5Gi') }}"

    - name: Fail on no Namespace definition provided
      debug:
        var: vars

    # Ensure we have the basic details 
    - name: Fail on no Namespace definition provided
      ansible.builtin.fail: 
        msg: "Cancelling Job, Namespace not correctly specified"
      when: ansible_facts["namespace"] is undefined or ansible_facts["namespace"] != ""

    # - fail: msg="Cancelling Job, Namespace does not exist on cluster"
    #   when: namespace is undefined

    # Override EDA Vars if Playbook has been initiated via EDA 
    - name: Include EDA Vars when defined
      ansible.builtin.include_tasks: 'var_list.yaml'
      when: ansible_eda is defined

    # Do the work...
    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ namespace }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
